### ISSUE TITLE
Adding users

### ISSUE THREAD

**Issue by nick-harper** [grzegab/camping#1]
Hi

I have just cloned this locally, I have done the migration to build the db but the users table is empty.

What should I use to add a user for testing? I have tried with md5 and sha1. What should the role be?

**Comment by grzegab** [comment]
Try adding 'add' method into UsersController.php line 19:
$this->Auth->allow(['logout']);
into
$this->Auth->allow(['logout', 'add]);

When done enter users/add to create user. When done remove 'add' method. And pass didn't work because it's using bcrypt with salt.

**Comment by grzegab** [comment]
Added default user to migrations with admin / admin credentials. Also added user options in panel layout.

**Comment by nick-harper** [comment]
Thanks, was just using this App to test an nginx server I had setup for speed. Works great!
